- slides/timeline/2019.md
- slides/topic/misc.md
Signed-off-by: Phil Huang <phil.huang@redhat.com>
> Add 20190720 Event Information

- slides/topic/cloud-native.md
> Add a new slide to Meetup #18

- slides/coscup/README.md
- slides/topic/cloud-native.md
> Add COSCUP Kubeflow slides

- slides/coscup/README.md
> [WIP] Add 2019 COSCUP all slides, close #12

- slides/timeline/2019.md
> Updated 2019 #19 08/31 meetups contents

- slides/timeline/2019.md
> Updated 建豪就收's slides link

- slides/topic/sdn.md
> Fix JianHao's slide link

- slides/timeline/2019.md
> Fix meetup#19 牛牛's slides link

- slides/timeline/2019.md
- slides/topic/sdn.md
Signed-off-by: Phil Huang <phil.huang@redhat.com>
> Add slide link from A10 Network Nick Chen 

- slides/timeline/2019.md
> Add 2019/09/28 meetups #20 contents

- slides/timeline/2018.md
- slides/topic/sdn.md
> Fix the title typo and dead link

- slides/timeline/2017.md
- slides/timeline/2018.md
- slides/topic/cloud-native.md
> Fix broken links

- slides/topic/cloud-native.md
> [CNTUG]Update info for meetup#20

- slides/timeline/2019.md
- slides/topic/cloud-native.md
> Updated meetup#20 Jie-Jhih's slides link

- .travis.yml
> Add awesome_bot for validating links

- slides/timeline/2019.md
- slides/topic/cloud-native.md
> Updated meetup#20 Alex's slide link

- slides/timeline/2019.md
- slides/topic/cloud-native.md
> Add SDN x Cloud Native Meetup #21 Slides

- slides/README.md
- slides/contribution-workshop/README.md
- slides/topic/cloud-native.md
- slides/topic/openstack.md
- slides/topic/sds.md
> Add contribution workshop #1 contents

- slides/coscup/README.md
- slides/timeline/2017.md
- slides/timeline/2018.md
- slides/timeline/2019.md
- slides/topic/cloud-native.md
- slides/topic/misc.md
- slides/topic/openstack.md
- slides/topic/sdn.md
- slides/topic/sds.md
Fixes #26.
- [ X] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
> Replace all redirect URL by its real URL

- slides/topic/cloud-native.md
- slides/topic/sdn.md
> Add Meetup#14 and #10 slides links into topic category

- .travis.yml
- slides/timeline/2017.md
- slides/timeline/2018.md
- slides/timeline/2019.md
- slides/topic/cloud-native.md
- slides/topic/sds.md
- slides/workshop/README.md
- Replace unusable slides links with TBA.
- Update contribution workshop #1 Kiefer Chang slides link.
- Modify `.travis.yml` (Add `tachingchen.com` to whitelist for solving the URL duplicate problem.)
---
> Fix some slides links issues

- slides/README.md
- slides/timeline/2020.md
- slides/topic/sdn.md
> Add the slide for meetup 24 and 2020 year

- slides/timeline/2020.md
> Add slides for meetup 25

- slides/timeline/2020.md
> Add slide for meetup 26 (jianhao slide)

- slides/timeline/2020.md
Add slide for meetup 26 (JackLin's slide)
> Add slide for meetup 26 (JackLin's slide)

- slides/README.md
- slides/online-only/2020.md
Add the new directory for the new style meetup content.
> Add the slide/youtube link for online-only meetup

- slides/online-only/2020.md
> [WIP] Add the slide for online meetup-2

- slides/timeline/2020.md
This commit adds links to Kubernetes Resource and Eviction Management slides presented by Ader Fu in meetup #28 on 5/20/2020.
I appreciate your invitation.
Give me the chance for public presention.thx.
> Add Slides for Meetup #28 (Ader Fu)

- slides/timeline/2020.md
This commit adds links to KubeVirt 101 slides presented by Gene Kuo in
meetup #28 on 5/20/2020.
> Add Slides for Meetup #28 (Gene Kuo)

- slides/timeline/2020.md
- slides/topic/cloud-native.md
- [X ] Fork [the repository](https://github.com/cloud-native-taiwan/meetups) and create your new branch from `master`.
- [X ] Use the present tense (Also in Pull Request title): "Add feature" not "Added feature"
- [ X] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
> Add meetup #27 slides and speakers

- slides/timeline/2020.md
> Fix indent

- slides/online-only/2020.md
> Add the slide for meetup-3

- slides/online-only/2020.md
Update the 4th meetup, including links of Youtube and slide.
> Update the 4th meetup

- slides/timeline/2020.md
@hazel-shen Would you mind collecting Meetup #30 slides?
> Add meetup 29 and 30

- slides/online-only/2020.md
> Fixs link to title

- slides/online-only/2020.md
> update online meetup

- slides/coscup/README.md
Add the COSCUP Agenda links that includes many on-site collaborative writing.
> Add COSCUP Agenda Link

- slides/timeline/2020.md
- slides/topic/cloud-native.md
- [V ] Fork [the repository](https://github.com/cloud-native-taiwan/meetups) and create your new branch from `master`.
- [V ] Please mention the name of community in Pull Request title.
- [V] Git Commit Messages
- [V ] Use the present tense (Also in Pull Request title): "Add feature" not "Added feature"
- [V ] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
- [V ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
> Add meetup#31 information

- slides/online-only/2020.md
Add the meetup information about the online meetup 6
- [ x] Fork [the repository](https://github.com/cloud-native-taiwan/meetups) and create your new branch from `master`.
- [ x] Please mention the name of community in Pull Request title.
- [x ] Git Commit Messages
- [x ] Use the present tense (Also in Pull Request title): "Add feature" not "Added feature"
- [ x] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
> Add meetup6

- slides/timeline/2020.md
* Add YouTube Links for meetup#32.
* Add title of meetup#32 and meetup#33
>  Add meetup #32 and #33 information

- slides/timeline/2020.md
> Update meetups #33 content - add YT and slides links

- slides/online-only/2020.md
- slides/topic/cloud-native.md
Update the slide and topic information for online event
https://www.meetup.com/CloudNative-Taiwan/events/275020442/
- [ o] Fork [the repository](https://github.com/cloud-native-taiwan/meetups) and create your new branch from `master`.
- [ o] Please mention the name of community in Pull Request title.
- [ o] Git Commit Messages
- [o ] Use the present tense (Also in Pull Request title): "Add feature" not "Added feature"
- [o] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
- [o] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
> Add slides and video for docker_k8s discussion

- slides/online-only/2020.md
> Add the meetup information about the online meetup 7

- slides/timeline/2021.md
* Update the content in meetup-35
> Add the information in meetup-35

- slides/timeline/2021.md
* Update the content in meetup-36.
* Fix the issue(#75).
> Add the information in meetup-35 and meetup-36. 

- slides/timeline/2021.md
* Update the content in meetup-37.
> Add the information in meetup-37

- slides/coscup/README.md
* Add the COSCUP 2021 Agenda links, topic, speaker and links.
> Add COSCUP 2021

- slides/timeline/2021.md
> Add slides of meetup-42

- slides/timeline/2021.md
* Update the yt link in meetup-42.
> Add the yt link in meetup-42

- README.md
- slides/timeline/2021.md
* Add the sildes in meetup 40 and 41.
* Add the OCF Donate link in README.md .
> Add the silde of meetup 40 and 41

- SPEAKER_GUIDE.md
- slides/timeline/2021.md
* Update the sildes in meetup 43.
* Fix to the tg link.
> Add the silde of meetup 43

- slides/kubernetes-community-days-2024/README.md
- [ x] Fork [the repository](https://github.com/cloud-native-taiwan/meetups) and create your new branch from `master`.
- [ x] Please mention the name of community in Pull Request title.
- [ x] Git Commit Messages
- [x ] Use the present tense (Also in Pull Request title): "Add feature" not "Added feature"
- [x ] Use the imperative mood (Also in Pull Request title): "Move cursor to..." not "Moves cursor to..."
- [x ] Use rebase to squash/fixup dummy/unnecessary commits into only one commit.
> Add slide KCD2024

- slides/kubernetes-community-days-taipei-2024/README.md
Separate agendas by date and format them into easy-to-read formats.
> Update KCD Taipei 2024 agenda and session details
